// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aeczgmvjlbdhdjkqzlet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlY3pnbXZqbGJkaGRqa3F6bGV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MzI2MzIsImV4cCI6MjA2MzMwODYzMn0.gTESWAV7CgxMX46kbqpsd9Rh7Hob7SL2_5OA4uRkZEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);